[package]
name = "treehouse"
version = "0.1.0"
authors = ["euvue <eeuv@tuta.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
